### ISSUE TITLE
Support TeamCity format

### ISSUE THREAD

**Issue by flcdrg** [Romanx/Cake.Coverlet#15]
Coverlet now supports a TeamCity output format. (See https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Reporters/TeamCityReporter.cs)

Would be nice to add this to the enum etc.

**Comment by Romanx** [comment]
This is great! thanks @flcdrg for the contribution. I'll push out a new release with this today.

**Comment by Romanx** [comment]
Turns out this was faster than I thought. It should be appearing on nuget shortly. Thanks for the PR 👍

**Comment by flcdrg** [comment]
Awesome, thanks for making it in the first place!

David

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
