### ISSUE TITLE
Coverlet.MSbuild.Tasks.InstrumentationTask hangs on build

### ISSUE THREAD

**Issue by eMarkM** [Romanx/Cake.Coverlet#23]
I have the following code in my cake build:

```
var testSettings = new DotNetCoreTestSettings()
{
    Configuration = configuration,
    NoBuild = true,
    ArgumentCustomization = args => args.Append($"--logger:trx /p:Exclude=\"[xunit.*]*\"")
};

var coverletSettings = new CoverletSettings {
    CollectCoverage = true,
    CoverletOutputFormat = CoverletOutputFormat.opencover,
    CoverletOutputDirectory = Directory(@".\coverage-results\"),
    CoverletOutputName = $"results-" + project.GetFilename()
};
DotNetCoreTest(project.FullPath, testSettings, coverletSettings);
```
Seems pretty straightforward and I've done this in a half dozen solutions and it runs great.  But in one particular solution, it's just a bit larger in size than the others, when I run this through Powershell, it just hangs on the DotNetCoreTest line.  When I break out, then PS starts giving me the following message over and over:

C:\myuserpath\.nuget\packages\coverlet.msbuild\2.5.1\build\netstandard2.0\coverlet.msbuild.targets(7,5): warning MSB4220: Waiting for the currently executing task "Coverlet.MSbuild.Tasks.InstrumentationTask" to cancel. [C:\Projects\my project path.csproj]

Any ideas what's going on here?  Not sure where to begin trying to debug this.  Thanks!

e

**Comment by eMarkM** [comment]
Realized this is probably an issue for Coverlet.Msbuild.  I'll post there as well.

**Comment by Romanx** [comment]
Hi there,

This does sound like a coverlet issue since we just pass the arguments through to msbuild or the global tool. I'll close this for now but if you find it's related to us then please feel free to comment
