### ISSUE TITLE
Coverlet does not generate any output files in cake

### ISSUE THREAD

**Issue by soroshsabz** [Romanx/Cake.Coverlet#30]
ITNOA

I have a project in [GitHub](https://github.com/BSVN/Commons) and have a [cake file](https://github.com/BSVN/Commons/blob/master/Build/build.cake) that use some code like below

```

        var coverletSettings = new CoverletSettings {
            CollectCoverage = true,
            CoverletOutputFormat = CoverletOutputFormat.opencover,
            CoverletOutputDirectory = Directory(@"./coverage-test/"),
            CoverletOutputName = coverageResultsFileName
        };

        DotNetCoreTest(testProject, settings, coverletSettings);
```

but when i run test target, we cannot found any coverage-test directory?

Did you can help me? what is my problem?

thanks

**Comment by Romanx** [comment]
Hi there, I can't see anything wrong with the settings. Is coverlet outputting anything to the console when the tests are run?

**Comment by soroshsabz** [comment]
@Romanx Thanks very much for reply, As you can see in [AppVeyor](https://ci.appveyor.com/project/soroshsabz/commons/builds/29452010) we cannot found coverage-test, in any directory?

**Comment by dweggemans** [comment]
If you forget to add coverlet.msbuild to the test project you get this behavior

**Comment by soroshsabz** [comment]
After I added this package I got a "Coverlet.MSbuild.Tasks.CoverageResultTask" task was not given a value for the required parameter "InstrumenterState"

**Comment by soroshsabz** [comment]
Thanks to @MarcoRossignoli I can resolved my issue
