### ISSUE TITLE
Using `Coverlet` alias fails when projects are built in Release configuration

### ISSUE THREAD

**Issue by AdmiringWorm** [Romanx/Cake.Coverlet#34]
Currently, when trying to use the `Coverlet` alias, and the test projects are built with the `Release` Configuration (or anything other than `Debug`) the addin is unable to find the necessary DLL to run `coverlet.console` it need.

This is because it seems to be hardcoded only to check the `Debug` folder.

Would it be possible to make the configuration to search for the DLL configurable?

**Comment by gitfool** [comment]
Also hitting this as we only run release builds on CI. Are you going to submit a PR, @AdmiringWorm? 😉

**Comment by AdmiringWorm** [comment]
That is something I definitely could do, if that is okay by @Romanx

**Comment by Romanx** [comment]
Sorry I'm just realising that I never replied to this so apologies.

This should be an easy fix but I haven't found time, we'd happily accept a PR @AdmiringWorm if you can

**Comment by AdmiringWorm** [comment]
Will open one as soon as I can (I expect on Sunday or Monday)

**Comment by Romanx** [comment]
Thanks @AdmiringWorm for the PR. Have just merged it and a new release should be out shortly with the configuration setting

**Comment by Romanx** [comment]
@AdmiringWorm sorry for the delay, this change was just released in version `2.5.1`. Thanks again!

**Comment by AdmiringWorm** [comment]
@Romanx No worries, thanks for creating a new release with the changes.
