### ISSUE TITLE
Update Cake.Coverlet to target Cake v1.0.0

### ISSUE THREAD

**Issue by augustoproiete** [Romanx/Cake.Coverlet#38]
https://cakebuild.net/blog/2021/02/cake-v1.0.0-released

**Comment by Romanx** [comment]
Hey,

Thanks for opening this issue. I should hopefully be able to find some time today to do this.

**Comment by augustoproiete** [comment]
Hey @Romanx I had a minute today and thought I'd put a PR in. Feel free to close it if you already have this working on a different branch.

**Comment by Romanx** [comment]
@augustoproiete thanks very much for the PR. I keep not finding time to do OSS.
