### ISSUE TITLE
Potential issue when adding cover report in a directory on Linux OS

### ISSUE THREAD

**Issue by mihai-neagoe-cko** [Romanx/Cake.Coverlet#4]
Using Coverlet addin 1.1.3

```
var path = @"./coverage-results";
EnsureDirectoryExists(path);
var curDir = MakeAbsolute(Directory(@"./coverage-results/"));
Information("Current directory is: {0}", curDir);

var coverletSettings = new CoverletSettings {
            CollectCoverage = true,
            CoverletOutputFormat = CoverletOutputFormat.opencover,
            CoverletOutputDirectory = curDir,
            CoverletOutputName = $"results"
};
```

Expected result
```
Calculating coverage result...
  Generating report '/home/BuildAgent/work/c0bd4777df028bc8/coverage-results/results.opencover.xml'
```

Actual result

```
Calculating coverage result...
   Generating report '/home/BuildAgent/work/c0bd4777df028bc8/coverage-resultsresults.opencover.xml'
```
![image](https://user-images.githubusercontent.com/28355018/43089682-33138e92-8e9d-11e8-8b4c-102a74621a44.png)

As you can see, it's not creating the report in the directory specified.

**Comment by Romanx** [comment]
Hi @mihai-neagoe-cko I think this is due to the output transformer defaulting to using a `\` slash rather than a `/` slash. Could you try the following setting to see if it fixes the problem?
```csharp
var coverletSettings = new CoverletSettings {
            CollectCoverage = true,
            CoverletOutputFormat = CoverletOutputFormat.opencover,
            CoverletOutputDirectory = curDir,
            OutputTransformer = (fileName, dir) => $@"{dir}/{fileName}";
            CoverletOutputName = $"results"
};
```

If that works then it should be an easy fix, thanks!

**Comment by Romanx** [comment]
Hi @mihai-neagoe-cko, I just pushed out a quick fix to nuget which should resolve this. Please let me know if it doesn't an i'll reopen.

Thanks for reporting it

**Comment by mihai-neagoe-cko** [comment]
You first suggestion, using the OutputTransaformer worked. I will revert back to what I had originally to see if the fix you pushed solve the issue.
