### ISSUE TITLE
Sonar not excluding files with attribute [ExcludeFromCodeCoverage]

### ISSUE THREAD

**Issue by Olegone23** [Romanx/Cake.Coverlet#45]
As mentioned Sonar not excluding files with attribute [ExcludeFromCodeCoverage] - Get help / SonarCloud - SonarSource Community it is because of a bug in Coverlet.

**Comment by Romanx** [comment]
Hi there,

We just pass through to coverlet itself so this sounds like an issue with them, infact similar to https://github.com/coverlet-coverage/coverlet/issues/1072. I'd recommend going over there and helping them repro the issue so it could be fixed.

Thanks
