### ISSUE TITLE
Update Cake.Coverlet add-in to target Cake v2.0.0

### ISSUE THREAD

**Issue by augustoproiete** [Romanx/Cake.Coverlet#47]
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

**Comment by sqeezy** [comment]
Is the reason for the missing upgrade the effort? I would be willing to provide a pull request.

**Comment by Romanx** [comment]
Superceeded by cake 3.0.0 bump. Thanks for the support on this!
