### ISSUE TITLE
Update Cake.Coverlet add-in to target Cake v3.0.0

### ISSUE THREAD

**Issue by augustoproiete** [Romanx/Cake.Coverlet#52]
[Cake 3.0.0](https://cakebuild.net/blog/2022/11/cake-v3.0.0-released) has been released  🎉

**Comment by Romanx** [comment]
Hey @augustoproiete 

Thanks for keeping on bumping me when these happen, i ended up down a yak shaving well when 2.0.0 was released.

I managed to salvage that work and bump to 3.0.0 and that's now pushed to nuget. Please let me know if you find any issues with the release.

**Comment by augustoproiete** [comment]
Great! Thanks a lot @Romanx !! 🚀
