### ISSUE TITLE
Add Tools/Aliases to call coverlet.exe directly

### ISSUE THREAD

**Issue by StanleyGoldman** [Romanx/Cake.Coverlet#7]
👋 Thanks for creating this project.

There are some scenarios where using `coverlet.msbuild` does not work and you need to use `coverlet.exe`. I was using this project until I realized that is my problem.

**Comment by Romanx** [comment]
Hi there,

Sorry for the delay on replying to this. I need to take a look to see how Cake handles external tools and possibly how to have this work with the dotnet global tools also.

**Comment by Romanx** [comment]
@StanleyGoldman I started taking a look at this and the work you started last night. Had some issues with getting coverlet to do what I wanted which i was debugging. I should hopefully be able to find some more time to look at it soon.

**Comment by StanleyGoldman** [comment]
Cool cool. Let me know if there is anything I can do to help.

**Comment by Romanx** [comment]
Hi @StanleyGoldman, i've merged this into master as 2.0. Thanks for the contribution and suggesting this idea!

**Comment by StanleyGoldman** [comment]
Thanks for implementing, sorry I never got a chance to test, been busy as heck.
I'll upgrade my stuffs soon when I get the chance.
